import {
    backgroundImageGenerateOptionsSchema,
    dialogGenerateOptionsSchema,
    elementImageGenerateOptionsSchema,
} from "@/ink/options-schema.generated";
import { logger } from "@/utils/log-utility";
import { ai, AIImageSprite, showDialog } from "@drincs/pixi-vn-ai";
import type {
    BackgroundImageGenerateOptions,
    DialogGenerateOptions,
    ElementImageGenerateOptions,
} from "@drincs/pixi-vn-ai";
import { canvas } from "@drincs/pixi-vn/canvas";
import { HashtagCommands } from "@drincs/pixi-vn-ink";
import {
    ENTRANCE_TRANSITION_TYPES,
    entranceTransitionKeySchemas,
    type EntranceTransitionType,
    executeEntranceTransition,
} from "@drincs/pixi-vn-json/actions";
import { z } from "zod";

/**
 * Splits the tail (everything after `<alias>`) of an `# ai background`/`# ai element` command
 * into its request string, free-form generate-options props, and an optional entrance
 * transition. Mirrors `@drincs/pixi-vn-spine`'s own `parseShowSpineTail`.
 */
export function parseAiShowTail(tail: string[]): {
    request: string | undefined;
    propsList: string[];
    transitionType?: EntranceTransitionType;
    transitionPropsList: string[];
} {
    const request = tail[0];
    let propsList = tail.slice(1);
    let transitionType: EntranceTransitionType | undefined;
    let transitionPropsList: string[] = [];
    const withIndex = propsList.indexOf("with");
    if (withIndex !== -1 && propsList.length > withIndex + 1) {
        const rawType = propsList[withIndex + 1];
        if ((ENTRANCE_TRANSITION_TYPES as readonly string[]).includes(rawType)) {
            transitionType = rawType as EntranceTransitionType;
            transitionPropsList = propsList.slice(withIndex + 2);
        }
        propsList = propsList.slice(0, withIndex);
    }

    return { request, propsList, transitionType, transitionPropsList };
}

/**
 * Shows a generated {@link AIImageSprite} on the canvas: runs the given entrance transition when
 * present, otherwise adds it directly (`canvas.add`), following the same "with <transition>"
 * pattern as `@drincs/pixi-vn-spine`'s `# show spine`.
 */
async function showGeneratedComponent(
    alias: string,
    component: AIImageSprite,
    transitionType: EntranceTransitionType | undefined,
    transitionPropsList: string[],
    convertListStringToObj: (listParm: string[]) => object,
    commandLabel: string,
): Promise<void> {
    if (transitionType) {
        let transitionProps: object | undefined;
        if (transitionPropsList.length > 0) {
            try {
                transitionProps = convertListStringToObj(transitionPropsList);
            } catch (e) {
                logger.error(`Failed to parse transition props for "${commandLabel}"`, e);
            }
        }
        await executeEntranceTransition(alias, component, transitionType, transitionProps);
    } else {
        canvas.add(alias, component);
    }
}

/**
 * Options for {@link createAiHandler}.
 */
export interface CreateAiHandlerOptions {
    /**
     * Known character ids — e.g. `characterIds` from the file generated by `vitePluginPixivn`'s
     * `assetsManifest` option, or simply your own registered character ids. When provided,
     * `# ai dialog as <character> ...` does a runtime membership check instead of accepting any
     * string. Mirrors `@drincs/pixi-vn-ink`'s own `addBaseHashtagCommands`' `assetAliasIds`/
     * `bundleIds` options.
     */
    characterIds?: readonly string[];
}

/**
 * Registers four Ink Hashtag-Commands that let Ink scripts drive `@drincs/pixi-vn-ai` directly:
 * `# ai background`, `# ai element` (both generate an image and show it as an
 * {@link AIImageSprite}, with an optional entrance transition), and two forms of `# ai dialog`
 * (generates a line of dialogue and sets it as the current narration dialogue, with or without a
 * speaking character). Mirrors `@drincs/pixi-vn-spine`'s own `createSpineHandler`.
 *
 * Call this once, near the start of your app (alongside e.g. `addBaseHashtagCommands`), before
 * any Ink content is parsed.
 *
 * @param options Optional configuration for known character ids — see
 *   {@link CreateAiHandlerOptions}.
 * @example
 * ```ink
 * # ai background bg "The throne room, lit by torches, a storm outside the windows." style "Oil painting" with dissolve duration 1
 * # ai element advisor "The advisor, an elderly man with a long grey beard." align { x: 0.75, y: 1 } with dissolve duration 1
 * # ai dialog as advisor "Greet the king with the bad news."
 * ```
 */
export function createAiHandler(options: CreateAiHandlerOptions = {}): void {
    function idSchema(
        ids: readonly string[] | undefined,
    ): z.ZodString | z.ZodEnum<Record<string, string>> {
        if (ids && ids.length > 0) {
            return z.enum(Object.fromEntries(ids.map((id) => [id, id])));
        }
        return z.string();
    }

    HashtagCommands.add(
        async (list, _props, convertListStringToObj) => {
            const alias = list[2];
            const { request, propsList, transitionType, transitionPropsList } = parseAiShowTail(
                list.slice(3),
            );
            if (!request) {
                logger.error(
                    `"ai background ${alias}" requires a request string, e.g. 'ai background ${alias} "The throne room."'`,
                );
                return true;
            }

            let options: BackgroundImageGenerateOptions = {};
            if (propsList.length > 0) {
                try {
                    options = convertListStringToObj(propsList) as BackgroundImageGenerateOptions;
                } catch (e) {
                    logger.error(`Failed to parse props for "ai background ${alias}"`, e);
                    return true;
                }
            }

            const generatedImage = await ai.image.generateBackground(request, options);
            const component = new AIImageSprite(undefined, generatedImage);
            await showGeneratedComponent(
                alias,
                component,
                transitionType,
                transitionPropsList,
                convertListStringToObj,
                `ai background ${alias}`,
            );
            return true;
        },
        {
            name: "AI show background",
            description: `Generates a background image from a natural language request (\`ai.image.generateBackground\`) and shows it on the canvas, with optional generate-options key/value properties (e.g. \`scene\`, \`style\`, \`context\`) and an optional entrance transition.

\`\`\`ink
# ai background <alias> <request> [<key> <value> …] [with dissolve|fade|movein|zoomin|pushin [<key> <value> …]]
\`\`\``,
            validation: z
                .tuple([z.literal("ai"), z.literal("background"), z.string()])
                .rest(z.string()),
            keySchemas: {
                with: {},
                ...entranceTransitionKeySchemas,
                4: backgroundImageGenerateOptionsSchema,
            },
        },
    );

    HashtagCommands.add(
        async (list, _props, convertListStringToObj) => {
            const alias = list[2];
            const { request, propsList, transitionType, transitionPropsList } = parseAiShowTail(
                list.slice(3),
            );
            if (!request) {
                logger.error(
                    `"ai element ${alias}" requires a request string, e.g. 'ai element ${alias} "The advisor."'`,
                );
                return true;
            }

            let options: ElementImageGenerateOptions = {};
            if (propsList.length > 0) {
                try {
                    options = convertListStringToObj(propsList) as ElementImageGenerateOptions;
                } catch (e) {
                    logger.error(`Failed to parse props for "ai element ${alias}"`, e);
                    return true;
                }
            }

            const generatedImage = await ai.image.generateElement(request, options);
            const component = new AIImageSprite(
                options.align ? { align: options.align } : undefined,
                generatedImage,
            );
            await showGeneratedComponent(
                alias,
                component,
                transitionType,
                transitionPropsList,
                convertListStringToObj,
                `ai element ${alias}`,
            );
            return true;
        },
        {
            name: "AI show element",
            description: `Generates a single visual element from a natural language request (\`ai.image.generateElement\`) and shows it on the canvas, positioned with \`align\` (the only supported way to position it — forwarded both to the generation prompt and to the canvas element itself) and an optional entrance transition.

\`\`\`ink
# ai element <alias> <request> [<key> <value> …] [with dissolve|fade|movein|zoomin|pushin [<key> <value> …]]
\`\`\``,
            validation: z
                .tuple([z.literal("ai"), z.literal("element"), z.string()])
                .rest(z.string()),
            keySchemas: {
                with: {},
                ...entranceTransitionKeySchemas,
                4: elementImageGenerateOptionsSchema,
            },
        },
    );

    HashtagCommands.add(
        async (list, _props, convertListStringToObj) => {
            const request = list[2];
            const propsList = list.slice(3);

            let options: DialogGenerateOptions = {};
            if (propsList.length > 0) {
                try {
                    options = convertListStringToObj(propsList) as DialogGenerateOptions;
                } catch (e) {
                    logger.error(`Failed to parse props for "ai dialog"`, e);
                    return true;
                }
            }

            await showDialog(request, undefined, options);
            return true;
        },
        {
            name: "AI show dialog",
            description: `Generates a dialogue from a natural language request (\`ai.text.generateDialog\`) and sets it as the current narration dialogue, with no speaking character, and optional generate-options key/value properties (e.g. \`scene\`, \`style\`, \`context\`).

\`\`\`ink
# ai dialog <request> [<key> <value> …]
\`\`\``,
            validation: z
                .tuple([z.literal("ai"), z.literal("dialog"), z.string()])
                .rest(z.string())
                .refine((arr) => arr[2] !== "as"),
            keySchemas: {
                3: dialogGenerateOptionsSchema,
            },
        },
    );

    HashtagCommands.add(
        async (list, _props, convertListStringToObj) => {
            const character = list[3];
            const request = list[4];
            const propsList = list.slice(5);

            let options: DialogGenerateOptions = {};
            if (propsList.length > 0) {
                try {
                    options = convertListStringToObj(propsList) as DialogGenerateOptions;
                } catch (e) {
                    logger.error(`Failed to parse props for "ai dialog as ${character}"`, e);
                    return true;
                }
            }

            await showDialog(request, character, options);
            return true;
        },
        {
            name: "AI show dialog with character",
            description: `Generates a dialogue from a natural language request (\`ai.text.generateDialog\`) and sets it as the current narration dialogue, with the given speaking character (also used as the prompt's \`speaker\` when not set among the key/value props), and optional generate-options key/value properties (e.g. \`scene\`, \`style\`, \`context\`).

\`\`\`ink
# ai dialog as <character> <request> [<key> <value> …]
\`\`\``,
            validation: z
                .tuple([
                    z.literal("ai"),
                    z.literal("dialog"),
                    z.literal("as"),
                    idSchema(options.characterIds),
                    z.string(),
                ])
                .rest(z.string()),
            keySchemas: {
                5: dialogGenerateOptionsSchema,
            },
        },
    );
}
