import {
    getTexture,
    ImageSprite,
    type ImageSpriteMemory,
    type ImageSpriteOptions,
    RegisteredCanvasComponents,
} from "@drincs/pixi-vn/canvas";
import type { Texture } from "@drincs/pixi-vn/pixi.js";

export const AI_IMAGE_SPRITE_ID = "AIImageSprite";

/**
 * Memory of an {@link AIImageSprite}: the same as {@link ImageSpriteMemory}, plus the generated
 * image itself.
 */
export interface AIImageSpriteMemory extends ImageSpriteMemory {
    /**
     * The image generated by `ai.image.generateBackground`/`ai.image.generateElement` that this
     * sprite is showing, as a data URI.
     */
    generatedImage?: string;
}

/**
 * An {@link ImageSprite} for images produced by `ai.image.generateBackground`/
 * `ai.image.generateElement`. It behaves exactly like {@link ImageSprite}, but also keeps the
 * generated image (a data URI) in its {@link memory}, so that save games store the generated
 * image itself and can restore the exact same image on load, instead of calling the AI provider
 * again (which would produce a different image).
 * @example
 * ```ts
 * const dataUri = await ai.image.generateBackground("The throne room, lit by torches.");
 * const sprite = new AIImageSprite(undefined, dataUri);
 * await sprite.load();
 * canvas.add("background", sprite);
 * ```
 */
export default class AIImageSprite<
    Memory extends AIImageSpriteMemory = AIImageSpriteMemory,
> extends ImageSprite<Memory> {
    readonly pixivnId: string = AI_IMAGE_SPRITE_ID;
    private _generatedImage?: string;

    /**
     * @param options The options for the component.
     * @param generatedImage The image generated by `ai.image.generateBackground`/
     *   `ai.image.generateElement`, as a data URI.
     */
    constructor(options?: ImageSpriteOptions | Omit<Texture, "on">, generatedImage?: string) {
        super(options, generatedImage);
        this._generatedImage = generatedImage;
    }

    /**
     * The generated image (a data URI) currently shown by this sprite, if any.
     */
    get generatedImage() {
        return this._generatedImage;
    }

    override get memory(): AIImageSpriteMemory {
        return {
            ...super.memory,
            pixivnId: this.pixivnId,
            generatedImage: this._generatedImage,
        };
    }

    override async setMemory(memory: Memory | ImageSpriteMemory): Promise<void> {
        if ("generatedImage" in memory && memory.generatedImage) {
            this._generatedImage = memory.generatedImage;
        }
        await super.setMemory(memory);
        if (this._generatedImage) {
            const texture = await getTexture(this._generatedImage);
            if (texture) {
                this.texture = texture;
            }
        }
    }
}
RegisteredCanvasComponents.add<AIImageSpriteMemory, typeof AIImageSprite>(AIImageSprite, {
    name: AI_IMAGE_SPRITE_ID,
});
